[[pages]]
path = "intro.py"
name = "Introduction"
icon = "🏠"


[[pages]]
path = "pages/1_glossary.py"
name = "Glossary"
icon = "🔮"

# [[pages]]
# path = "pages/2_tools.py"
# name = "Must-know"
# icon = "🛠"

[[pages]]
path = "pages/3_cake_eating_finite.py"
name = "Cake Eating - Finite"
icon = "🎂"

[[pages]]
path = "pages/4_cake_eating_infinite.py"
name = "Cake Eating - Infinite"
icon = "🍰"