[[pages]]
path = "intro.py"
name = "Introduction"
icon = "🏠"

[[pages]]
path = "pages/0_tools.py"
name = "Must-know"
icon = "🛠"

[[pages]]
path = "pages/1_cake_eating.py"
name = "Cake Eating"
icon = "🍰"